env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "DATABRICKS_PIXELS_TABLE"
    value: "main.pixels_solacc.object_catalog"
  - name: "LAKEBASE_INSTANCE_NAME"
    value: "pixels-lakebase"