env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "warehouse_id"
  - name: "DATABRICKS_PIXELS_TABLE"
    valueFrom: "pixels_table"
  - name: "LAKEBASE_INSTANCE_NAME"
    valueFrom: "lakebase_instance"
  - name: "DATABRICKS_STOW_VOLUME_PATH"
    valueFrom: "stow_volume_path"
