env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql_warehouse"
  - name: "MONAI_SERVING_ENDPOINT"
    valueFrom: "serving_endpoint"
  - name: "DATABRICKS_PIXELS_TABLE"
    value: "{PIXELS_TABLE}"
  - name: "LAKEBASE_INSTANCE_NAME"
    value: "{LAKEBASE_INSTANCE_NAME}"
  - name: "LAKEBASE_DICOM_FRAMES_TABLE"
    value: "dicom_frames"