env:
  - name: "SQL_WAREHOUSE_ID"
    valueFrom: "sqlwarehouse"
  - name: "MONAI_SERVING_ENDPOINT"
    valueFrom: "serving_endpoint"
  - name: "DATABRICKS_PIXELS_TABLE"
    value: "main.pixels_solacc.object_catalog"
